apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloomblog-publish-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: publish
  template:
    metadata:
      labels:
        app: publish
    spec:
      containers:
        - name: bloomblog-publish
          image: registry.digitalocean.com/bloomblog/bloomblog-publish:latest
          imagePullPolicy: Always
          # TODO Replace the tokens to your aws tokens, you can also use S3 with
          # TODO changing the host and port of the S3 config, the apis are compatible
          env:
            - name: AWS_ACCESS_KEY_ID
              value: ${{ secrets.AWS_ACCESS_KEY_ID }}
            - name: AWS_SECRET_ACCESS_KEY
              value: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ports:
            - containerPort: 8084
          resources:
            requests:
              cpu: "10m"