apiVersion: v1
kind: Service
metadata:
  name: bloomblog-server
spec:
  selector:
    app: api  # 确保与 Pod 的标签一致
  ports:
    - protocol: TCP
      port: 8088         # LoadBalancer 暴露的端口
      targetPort: 8088   # Pod 内部应用的监听端口
  type: LoadBalancer      # 定义为 LoadBalancer 类型