apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloomblog-user-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: bloomblog-user
          image: registry.digitalocean.com/bloomblog/bloomblog-user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "10m"