apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloomblog-comment-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
        - name: bloomblog-comment
          image: registry.digitalocean.com/bloomblog/bloomblog-comment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          resources:
            requests:
              cpu: "10m"